openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  '/document-categories':
    get:
      summary: Get Document Categories
      operationId: getDocumentCategories
      tags:
        - document categories
      responses:
        '200':
          description: Document Categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentCategoryDTO'

components:
  schemas:
    DocumentCategoryDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string

