openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1'
paths:
  '/exam/{id}':
    get:
      summary: Get Exams By Category Id. Show title and Level of Exams
      operationId: getExams
      tags:
        - exams
      parameters:
        - name: id
          in: path
          description: 'id of category'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/examDTO'
  '/exam':
    post:
      summary: Get mark of exam
      operationId: getMark
      tags:
        - exams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExamRequest'
      responses:
        '200':
          description: Get-Mark
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResultDTO'

components:
  schemas:
    ExamRequest:
      type: object
      properties:
        id_exam:
          type: integer
        list_answer:
          $ref: '#/components/schemas/ListAnswer'
    ListAnswer:
      type: array
      items:
        $ref: '#/components/schemas/SubList'
    SubList:
      type: object
      properties:
        id_question:
          type: integer
        answer:
          type: integer

    examDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        categoryId:
          type: integer
        isRandom:
          type: integer
        isDone:
          type: integer
        isFree:
          type: integer
        level:
          type: integer

    TestResultDTO:
      type: object
      properties:
        title:
          type: string
          description: title of category
        id_theory:
          type: integer
          description: id of theory get by category title
        total_question_of_cat:
          type: integer
          description: total question which belong to category
        selected_question_true:
          type: integer
          description: list question which belong to category
        total_question_true:
          type: integer
          description: total question true of exam
        total_question:
          type: integer
          description: total question of exam
        list_answer:
          $ref: '#/components/schemas/AnswerOfCat'
    AnswerOfCat:
      type: array
      items:
        $ref: '#/components/schemas/Answers'
    Answers:
      type: object
      properties:
        question_number:
          type: integer
          description: index of question in exam
        is_right:
          type: integer
          description: question is true(1) or false(0)

