openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1'
paths:
  '/exams/{id}':
    get:
      summary: Get Exams By Category Id. Show title and Level of Exams
      operationId: getExams
      tags:
        - exams
      parameters:
        - name: id
          in: path
          description: 'id of category'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Exams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/examDTO'

components:
  schemas:
    examDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        categoryId:
          type: integer
        level:
          type: integer


