openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1'
paths:
  '/feels':
    get:
      summary: Get Feels
      operationId: getFeels
      tags:
        - feels
      responses:
        '200':
          description: Feels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/feelDTO'

components:
  schemas:
    feelDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        thumbnail:
          type: string
        despication:
          type: string
        contents:
          type: string

