openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  '/test-history':
    post:
      summary: Create test history
      operationId: createTestHistory
      tags:
        - test-history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestHistoryCreateRequest'
      responses:
        '200':
          description: Test history has created
  '/test-history/{id}':
    get:
      summary: View test result
      operationId: getTestResult
      tags:
        - test-history
      parameters:
        - name: id
          in: path
          description: 'id of history'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-Result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResultDTO'

components:
  schemas:
    TestHistoryCreateRequest:
      type: object
      properties:
        id_exam:
          type: integer
        type:
          type: integer
        test_schedules_id:
          type: integer
        list_answer:
          $ref: '#/components/schemas/ListAnswer'
    ListAnswer:
      type: array
      items:
        $ref: '#/components/schemas/SubList'
    SubList:
      type: object
      properties:
        id_question:
          type: integer
        answer:
          type: integer
    TestResultDTO:
      type: object
      properties:
        title:
          type: string
        total_question:
          type: integer
        selected_question:
          type: integer
        list_answer:
          $ref: '#/components/schemas/AnswerOfCat'
    AnswerOfCat:
      type: array
      items:
        $ref: '#/components/schemas/Answers'
    Answers:
      type: object
      properties:
        question_number:
          type: integer
        is_right:
          type: integer


