openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  '/test-history':
    post:
      summary: Create test history
      operationId: createTestHistory
      tags:
        - test-history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestHistoryCreateRequest'
      responses:
        '200':
          description: Test history has created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdHistory'

  '/test-history/{id}':
    get:
      summary: View test result
      operationId: getTestResult
      tags:
        - test-history
      parameters:
        - name: id
          in: path
          description: 'id of history'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-Result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResultDTO'

components:
  schemas:
    TestHistoryCreateRequest:
      type: object
      properties:
        id_exam:
          type: integer
        type:
          type: integer
        test_schedules_id:
          type: integer
        list_answer:
          $ref: '#/components/schemas/ListAnswer'
    ListAnswer:
      type: array
      items:
        $ref: '#/components/schemas/SubList'
    SubList:
      type: object
      properties:
        id_question:
          type: integer
        answer:
          type: integer
    TestResultDTO:
      type: object
      properties:
        title:
          type: string
          description: title of category
        id_theory:
          type: integer
          description: id of theory get by category title
        total_question_of_cat:
          type: integer
          description: total question which belong to category
        selected_question_true:
          type: integer
          description: list question which belong to category
        total_question_true:
          type: integer
          description: total question true of exam
        total_question:
          type: integer
          description: total question of exam
        list_answer:
          $ref: '#/components/schemas/AnswerOfCat'
    AnswerOfCat:
      type: array
      items:
        $ref: '#/components/schemas/Answers'
    Answers:
      type: object
      properties:
        question_number:
          type: integer
          description: index of question in exam
        is_right:
          type: integer
          description: question is true(1) or false(0)

    IdHistory:
      type: integer

