openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  '/theorys/{id}':
    get:
      summary: Get Theory By Id
      operationId: getTheory
      tags:
        - theory
      parameters:
        - name: id
          in: path
          description: 'id of theory'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Theory
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theoryDTO'

components:
  schemas:
    theoryDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        contents:
          type: string
        examId:
          type: integer
        categoryId:
          type: integer
        categoryPath:
          type: string



#openapi: 3.0.1
#info:
#  title: "Hava Project - REST API documents"
#  version: 1.0.0
#servers:
#  - url: 'http://localhost:8080/api/v1'
#paths:
#  '/documents':
#    get:
#      summary: Get Documents
#      operationId: getDocuments
#      tags:
#        - documents
#      responses:
#        '200':
#          description: Documents
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: '#/components/schemas/DocumentDTO'
#
#components:
#  schemas:
#    DocumentDTO:
#      type: object
#      properties:
#        id:
#          type: integer
#        title:
#          type: string
#        thumbnail:
#          type: string
#        href:
#          type: string
#        document_category_id:
#          type: integer
#


