openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1'
paths:
  '/category/{id}':
    get:
      summary: Get Category By Parent Id
      operationId: getCategory
      tags:
        - theory
      parameters:
        - name: id
          in: path
          description: 'id is parent_id in [categories] table and category_id in [theories] table too'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/categoryDTO'
  '/theory/{id}':
    get:
      summary: Get Theory By Id
      operationId: getTheory
      tags:
        - theory
      parameters:
        - name: id
          in: path
          description: 'id of theory'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Theory
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theoryDTO'

components:
  schemas:
    categoryDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        examId:
          type: integer
        contents:
          type: string
    theoryDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        contents:
          type: string
        examId:
          type: integer
        categoryId:
          type: integer
