openapi: 3.0.1
info:
  title: "Hava Project - REST API documents"
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  '/videos':
    get:
      summary: Get Videos
      operationId: getVideos
      tags:
        - videos
      responses:
        '200':
          description: Videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoDTO'

components:
  schemas:
    VideoDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        thumbnail:
          type: string
        href:
          type: string
        contents:
          type: string

