server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hava
    username: root
    password: 20091999
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


swagger2:
  title: HAVA BE - REST API
  description: HAVA - REST API documentation
  version: 1.0.0
  url-view: '/v2/api-docs,/configuration/**,/swagger-resources/**,/swagger-ui.html,/webjars/**'

